
create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;

create or replace function private.set_updated_at()
returns trigger language plpgsql security invoker set search_path=''
as $$ begin new.updated_at=now(); return new; end; $$;

create or replace function private.try_uuid(p_text text)
returns uuid language plpgsql immutable security invoker set search_path=''
as $$
begin
  if p_text is null or btrim(p_text)='' then return null; end if;
  return p_text::uuid;
exception when invalid_text_representation then return null;
end;
$$;

create table public.projects (
 id uuid primary key default gen_random_uuid(),
 code text, name text not null, full_name text,
 status text not null default 'active' check(status in('active','archived')),
 created_by uuid default auth.uid(),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table public.project_members (
 project_id uuid not null references public.projects(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 access_role text not null default 'editor' check(access_role in('owner','editor','viewer')),
 permissions jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 primary key(project_id,user_id)
);

create table public.project_files (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 bucket_id text not null default 'project-files',
 storage_path text not null, original_name text not null, mime_type text,
 size_bytes bigint, sha256 text, category text,
 uploaded_by uuid default auth.uid(), created_at timestamptz not null default now(),
 unique(project_id,storage_path)
);

create table public.project_file_links (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 file_id uuid not null references public.project_files(id) on delete cascade,
 entity_type text not null, entity_id uuid not null,
 relation_role text not null default 'attachment', sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 unique(file_id,entity_type,entity_id,relation_role)
);

create table public.imports (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 domain text not null,
 source_file_id uuid references public.project_files(id) on delete set null,
 source_name text, source_period date,
 status text not null default 'loaded' check(status in('loaded','applied','rejected','archived')),
 report jsonb not null default '{}'::jsonb,
 imported_by uuid default auth.uid(), imported_at timestamptz not null default now()
);

create table public.import_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 import_id uuid not null references public.imports(id) on delete cascade,
 source_row_no integer, source_key text,
 raw_data jsonb not null default '{}'::jsonb,
 normalized_data jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create table public.audit_events (
 id bigint generated by default as identity primary key,
 project_id uuid not null references public.projects(id) on delete cascade,
 actor_user_id uuid default auth.uid(),
 domain text not null, action text not null, entity_type text, entity_id uuid,
 payload jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create table public.catalog_items (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 mark text not null, name text not null, normalized_key text, archived_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(project_id,mark,name)
);

create table public.specification_sections (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 building_section text not null, zone text not null, name text not null,
 sort_order integer not null default 0, is_stairs boolean not null default false,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.specification_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 section_id uuid not null references public.specification_sections(id) on delete restrict,
 catalog_item_id uuid references public.catalog_items(id) on delete restrict,
 position_no integer not null, designation text,
 length_mm numeric(16,3), width_mm numeric(16,3), thickness_mm numeric(16,3),
 area_m2 numeric(18,6), project_volume_m3 numeric(18,6), mass_kg numeric(18,3),
 sort_order integer not null default 0,
 source_import_id uuid references public.imports(id) on delete set null,
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 source_original jsonb not null default '{}'::jsonb,
 archived_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index ux_specification_rows_position_active
 on public.specification_rows(project_id,position_no) where archived_at is null;

create table public.specification_quantities (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 specification_row_id uuid not null references public.specification_rows(id) on delete cascade,
 level_code text not null, level_order integer not null,
 quantity numeric(20,6) not null default 0 check(quantity>=0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(specification_row_id,level_code)
);

create table public.estimates (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 number text not null, name text,
 status text not null default 'active' check(status in('active','archived')),
 source_import_id uuid references public.imports(id) on delete set null,
 imported_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(project_id,number)
);

create table public.estimate_sections (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_id uuid not null references public.estimates(id) on delete cascade,
 title text not null, occurrence integer not null default 1, sort_order integer not null default 0,
 source_row_no integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.estimate_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_id uuid not null references public.estimates(id) on delete cascade,
 section_id uuid references public.estimate_sections(id) on delete restrict,
 row_type text not null check(row_type in('work','material')),
 position text, basis text, name text not null, unit text, quantity numeric(20,6),
 sort_order integer not null default 0, source_row_no integer,
 source_import_id uuid references public.imports(id) on delete set null,
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 source_original jsonb not null default '{}'::jsonb, archived_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.estimate_row_costs (
 estimate_row_id uuid primary key references public.estimate_rows(id) on delete cascade,
 project_id uuid not null references public.projects(id) on delete cascade,
 salary_unit numeric(20,6) not null default 0, salary_amount numeric(20,6) not null default 0,
 machines_unit numeric(20,6) not null default 0, machines_amount numeric(20,6) not null default 0,
 drivers_unit numeric(20,6) not null default 0, drivers_amount numeric(20,6) not null default 0,
 materials_unit numeric(20,6) not null default 0, materials_amount numeric(20,6) not null default 0,
 transport_unit numeric(20,6) not null default 0, transport_amount numeric(20,6) not null default 0,
 total_unit numeric(20,6) not null default 0, total_amount numeric(20,6) not null default 0,
 updated_at timestamptz not null default now()
);

create table public.estimate_notes (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_id uuid not null references public.estimates(id) on delete cascade,
 source_row_no integer, sort_order integer not null default 0,
 text text not null, source_original jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create table public.reconciliation_links (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_row_id uuid not null references public.estimate_rows(id) on delete cascade,
 specification_row_id uuid not null references public.specification_rows(id) on delete cascade,
 link_method text not null default 'auto' check(link_method in('auto','manual')),
 origin_mode text, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(estimate_row_id,specification_row_id)
);

create table public.reconciliation_journal (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_row_id uuid references public.estimate_rows(id) on delete set null,
 specification_row_id uuid references public.specification_rows(id) on delete set null,
 issue_key text, reasons text[] not null default '{}', proposal text, comment text,
 status text not null default 'open' check(status in('open','clarification','accepted','closed')),
 snapshot jsonb not null default '{}'::jsonb, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.estimate_work_links (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 material_row_id uuid not null references public.estimate_rows(id) on delete cascade,
 work_row_id uuid not null references public.estimate_rows(id) on delete cascade,
 link_method text not null default 'auto' check(link_method in('auto','manual')),
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(material_row_id,work_row_id), check(material_row_id<>work_row_id)
);

create table public.current_price_settings (
 project_id uuid primary key references public.projects(id) on delete cascade,
 overhead_percent numeric(12,6) not null default 109.31,
 profit_percent numeric(12,6) not null default 105.63,
 temporary_percent numeric(12,6) not null default 3.70,
 temporary_coefficient numeric(12,6) not null default 0.93,
 winter_percent numeric(12,6) not null default 2.5740,
 winter_coefficient numeric(12,6) not null default 0.93,
 insurance_percent numeric(12,6) not null default 34,
 travel_percent numeric(12,6) not null default 0,
 tender_coefficient numeric(12,6) not null default 1,
 forecast_index numeric(12,6) not null default 1.0552,
 vat_percent numeric(12,6) not null default 0,
 temporary_return_percent numeric(12,6),
 updated_by uuid default auth.uid(), updated_at timestamptz not null default now(),
 check(forecast_index>=0), check(tender_coefficient>=0)
);

create table public.current_price_row_overrides (
 estimate_row_id uuid primary key references public.estimate_rows(id) on delete cascade,
 project_id uuid not null references public.projects(id) on delete cascade,
 overhead_percent numeric(12,6), profit_percent numeric(12,6),
 temporary_percent numeric(12,6), temporary_coefficient numeric(12,6),
 winter_percent numeric(12,6), winter_coefficient numeric(12,6),
 insurance_percent numeric(12,6), travel_percent numeric(12,6),
 rule_code text, note text, updated_by uuid default auth.uid(),
 updated_at timestamptz not null default now()
);

create table public.current_price_revisions (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 estimate_id uuid not null references public.estimates(id) on delete cascade,
 revision_no integer not null, settings_snapshot jsonb not null,
 is_current boolean not null default false,
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 unique(estimate_id,revision_no)
);
create unique index ux_current_price_revision_one_current
 on public.current_price_revisions(estimate_id) where is_current;

create table public.current_price_row_results (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 revision_id uuid not null references public.current_price_revisions(id) on delete cascade,
 estimate_row_id uuid not null references public.estimate_rows(id) on delete cascade,
 quantity numeric(20,6),
 salary numeric(20,6) not null default 0, machines numeric(20,6) not null default 0,
 drivers numeric(20,6) not null default 0, transport numeric(20,6) not null default 0,
 materials numeric(20,6) not null default 0, direct_cost numeric(20,6) not null default 0,
 overhead numeric(20,6) not null default 0, profit numeric(20,6) not null default 0,
 temporary numeric(20,6) not null default 0, winter numeric(20,6) not null default 0,
 construction_works numeric(20,6) not null default 0, insurance numeric(20,6) not null default 0,
 travel numeric(20,6) not null default 0, other_costs numeric(20,6) not null default 0,
 total_construction_works numeric(20,6) not null default 0,
 temporary_return numeric(20,6) not null default 0,
 contractor_total numeric(20,6) not null default 0,
 with_tender numeric(20,6) not null default 0, with_forecast numeric(20,6) not null default 0,
 with_tender_and_forecast numeric(20,6) not null default 0,
 vat numeric(20,6) not null default 0, total_with_vat numeric(20,6) not null default 0,
 unit_price_at_start numeric(20,8), created_at timestamptz not null default now(),
 unique(revision_id,estimate_row_id)
);

create table public.gpr_plans (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 name text not null default 'График производства работ',
 status text not null default 'draft' check(status in('draft','active','archived')),
 start_month date, end_month date, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(start_month is null or date_trunc('month',start_month)::date=start_month),
 check(end_month is null or date_trunc('month',end_month)::date=end_month)
);

create table public.gpr_plan_estimates (
 project_id uuid not null references public.projects(id) on delete cascade,
 plan_id uuid not null references public.gpr_plans(id) on delete cascade,
 estimate_id uuid not null references public.estimates(id) on delete cascade,
 pricing_revision_id uuid references public.current_price_revisions(id) on delete restrict,
 created_at timestamptz not null default now(), primary key(plan_id,estimate_id)
);

create table public.gpr_months (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 plan_id uuid not null references public.gpr_plans(id) on delete cascade,
 month date not null, execution_index numeric(12,6) not null default 1,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(plan_id,month),
 check(date_trunc('month',month)::date=month), check(execution_index>=0)
);

create table public.gpr_floor_assignments (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 plan_id uuid not null references public.gpr_plans(id) on delete cascade,
 month_id uuid not null references public.gpr_months(id) on delete cascade,
 building_section text not null default 'all', level_code text not null,
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(plan_id,building_section,level_code)
);

create table public.gpr_row_assignments (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 plan_id uuid not null references public.gpr_plans(id) on delete cascade,
 month_id uuid not null references public.gpr_months(id) on delete cascade,
 estimate_row_id uuid not null references public.estimate_rows(id) on delete cascade,
 quantity numeric(20,6) not null,
 source_mode text not null check(source_mode in('floor','linked_work','manual')),
 source_specification_row_id uuid references public.specification_rows(id) on delete set null,
 source_level_code text,
 parent_assignment_id uuid references public.gpr_row_assignments(id) on delete set null,
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(), check(quantity>=0)
);

create table public.suppliers (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 name text not null, archived_at timestamptz,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.supplier_items (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 supplier_id uuid references public.suppliers(id) on delete restrict,
 catalog_item_id uuid references public.catalog_items(id) on delete restrict,
 source_mark text not null, source_name text not null, source_section text, source_key text,
 unit_volume_m3 numeric(18,6),
 link_method text check(link_method in('auto','manual')),
 link_state text not null default 'unmatched' check(link_state in('matched','review','unmatched')),
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 archived_at timestamptz, created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table public.supplier_prices (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 supplier_item_id uuid not null references public.supplier_items(id) on delete cascade,
 effective_from date not null, price_basis text not null check(price_basis in('piece','m3')),
 unit_price_gross numeric(20,6) not null check(unit_price_gross>=0),
 unit_volume_snapshot_m3 numeric(18,6),
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 created_at timestamptz not null default now(),
 unique(supplier_item_id,effective_from,price_basis,unit_price_gross)
);

create table public.supply_documents (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 supplier_id uuid references public.suppliers(id) on delete restrict,
 document_type text not null check(document_type in('white','green')),
 receipt_date date not null, ttn_number text,
 status text not null default 'posted' check(status in('draft','posted','cancelled')),
 note text, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.supply_document_lines (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 document_id uuid not null references public.supply_documents(id) on delete cascade,
 sort_order integer not null default 0, source_mark text, source_name text,
 catalog_item_id uuid references public.catalog_items(id) on delete restrict,
 supplier_item_id uuid references public.supplier_items(id) on delete restrict,
 qty_pieces numeric(20,6), qty_m3 numeric(20,6), unit_volume_snapshot_m3 numeric(18,6),
 price_basis text check(price_basis in('piece','m3')), unit_price numeric(20,6),
 amount_net numeric(20,6), vat_percent numeric(12,6) not null default 0,
 vat_amount numeric(20,6), amount_gross numeric(20,6),
 match_state text not null default 'unmatched' check(match_state in('matched','review','unmatched')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(qty_pieces is null or qty_pieces>=0), check(qty_m3 is null or qty_m3>=0),
 check(unit_price is null or unit_price>=0)
);

create table public.supply_line_allocations (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 white_line_id uuid not null references public.supply_document_lines(id) on delete cascade,
 green_line_id uuid not null references public.supply_document_lines(id) on delete cascade,
 allocated_pieces numeric(20,6), allocated_m3 numeric(20,6),
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(white_line_id,green_line_id), check(white_line_id<>green_line_id),
 check(allocated_pieces is null or allocated_pieces>=0),
 check(allocated_m3 is null or allocated_m3>=0)
);

create table public.montage_events (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 specification_row_id uuid not null references public.specification_rows(id) on delete restrict,
 level_code text not null, event_date date not null,
 event_type text not null default 'fact' check(event_type in('plan','fact')),
 quantity numeric(20,6) not null check(quantity>0), note text,
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table public.avr_documents (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 period_month date not null, display_number text,
 created_by uuid default auth.uid(), created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(), unique(project_id,period_month),
 check(date_trunc('month',period_month)::date=period_month)
);

create table public.avr_versions (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 document_id uuid not null references public.avr_documents(id) on delete cascade,
 version_no integer not null,
 state text not null default 'draft' check(state in('draft','in_use','signed')),
 source_import_id uuid references public.imports(id) on delete set null,
 signed_at timestamptz, signed_by uuid, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), unique(document_id,version_no)
);
create unique index ux_avr_one_in_use_version on public.avr_versions(document_id) where state='in_use';
create unique index ux_avr_one_signed_version on public.avr_versions(document_id) where state='signed';

create table public.avr_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 version_id uuid not null references public.avr_versions(id) on delete cascade,
 estimate_row_id uuid not null references public.estimate_rows(id) on delete restrict,
 quantity numeric(20,6) not null default 0, quantity_m3 numeric(20,6),
 amount numeric(20,6) not null default 0,
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 created_at timestamptz not null default now(),
 unique(version_id,estimate_row_id), check(quantity>=0)
);

create table public.accounting_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 import_id uuid not null references public.imports(id) on delete cascade,
 source_import_row_id uuid references public.import_rows(id) on delete set null,
 account_code text, material_code text not null, name text not null, unit text,
 quantity numeric(20,6), unit_price numeric(20,6), amount numeric(20,6),
 source_row_no integer, created_at timestamptz not null default now()
);

create table public.accounting_code_links (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 accounting_code text not null,
 catalog_item_id uuid not null references public.catalog_items(id) on delete restrict,
 link_method text not null default 'manual' check(link_method in('auto','manual')),
 note text, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(project_id,accounting_code)
);

create table public.accounting_period_sources (
 project_id uuid not null references public.projects(id) on delete cascade,
 period_month date not null, import_id uuid not null references public.imports(id) on delete restrict,
 selected_by uuid default auth.uid(), selected_at timestamptz not null default now(),
 primary key(project_id,period_month),
 check(date_trunc('month',period_month)::date=period_month)
);

create table public.s29_documents (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 period_month date not null,
 avr_version_id uuid not null references public.avr_versions(id) on delete restrict,
 accounting_import_id uuid not null references public.imports(id) on delete restrict,
 status text not null default 'draft' check(status in('draft','fixed')),
 fixed_at timestamptz, fixed_by uuid, created_by uuid default auth.uid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(project_id,period_month), check(date_trunc('month',period_month)::date=period_month)
);

create table public.s29_rows (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 document_id uuid not null references public.s29_documents(id) on delete cascade,
 catalog_item_id uuid not null references public.catalog_items(id) on delete restrict,
 avr_quantity_pieces numeric(20,6) not null default 0,
 volume_per_piece_snapshot_m3 numeric(18,6) not null,
 avr_quantity_m3 numeric(20,6) not null default 0,
 written_off_m3 numeric(20,6) not null default 0,
 economy_m3 numeric(20,6) not null default 0,
 overrun_m3 numeric(20,6) not null default 0,
 note text, created_at timestamptz not null default now(),
 unique(document_id,catalog_item_id)
);

create table public.s29_allocations (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 s29_row_id uuid not null references public.s29_rows(id) on delete cascade,
 accounting_row_id uuid not null references public.accounting_rows(id) on delete restrict,
 allocated_m3 numeric(20,6) not null check(allocated_m3>0),
 created_at timestamptz not null default now(), unique(s29_row_id,accounting_row_id)
);

create table public.s29_carryovers (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 origin_document_id uuid not null references public.s29_documents(id) on delete restrict,
 origin_row_id uuid not null references public.s29_rows(id) on delete restrict,
 catalog_item_id uuid not null references public.catalog_items(id) on delete restrict,
 kind text not null check(kind in('economy','overrun')),
 origin_month date not null, created_m3 numeric(20,6) not null check(created_m3>0),
 created_at timestamptz not null default now(),
 check(date_trunc('month',origin_month)::date=origin_month)
);

create table public.s29_carryover_settlements (
 id uuid primary key default gen_random_uuid(),
 project_id uuid not null references public.projects(id) on delete cascade,
 carryover_id uuid not null references public.s29_carryovers(id) on delete restrict,
 settlement_document_id uuid not null references public.s29_documents(id) on delete restrict,
 settlement_month date not null, settled_m3 numeric(20,6) not null check(settled_m3>0),
 created_at timestamptz not null default now(),
 check(date_trunc('month',settlement_month)::date=settlement_month)
);

create view public.v_s29_carryover_balances with(security_invoker=true) as
select c.id,c.project_id,c.catalog_item_id,c.kind,c.origin_month,c.created_m3,
 coalesce(sum(s.settled_m3),0)::numeric(20,6) settled_m3,
 (c.created_m3-coalesce(sum(s.settled_m3),0))::numeric(20,6) remaining_m3
from public.s29_carryovers c
left join public.s29_carryover_settlements s on s.carryover_id=c.id
group by c.id,c.project_id,c.catalog_item_id,c.kind,c.origin_month,c.created_m3;

create index ix_project_members_user on public.project_members(user_id,project_id);
create index ix_project_files_project on public.project_files(project_id,category);
create index ix_imports_project_domain on public.imports(project_id,domain,imported_at desc);
create index ix_import_rows_import on public.import_rows(import_id,source_row_no);
create index ix_audit_project_time on public.audit_events(project_id,created_at desc);
create index ix_catalog_project_mark on public.catalog_items(project_id,mark);
create index ix_spec_sections_project_order on public.specification_sections(project_id,sort_order);
create index ix_spec_rows_project_section on public.specification_rows(project_id,section_id,sort_order);
create index ix_spec_rows_catalog on public.specification_rows(catalog_item_id) where archived_at is null;
create index ix_spec_qty_row_order on public.specification_quantities(specification_row_id,level_order);
create index ix_estimates_project on public.estimates(project_id,number);
create index ix_estimate_sections_order on public.estimate_sections(estimate_id,sort_order);
create index ix_estimate_rows_order on public.estimate_rows(estimate_id,sort_order) where archived_at is null;
create index ix_estimate_rows_type on public.estimate_rows(project_id,row_type) where archived_at is null;
create index ix_recon_estimate on public.reconciliation_links(estimate_row_id);
create index ix_recon_spec on public.reconciliation_links(specification_row_id);
create index ix_work_links_material on public.estimate_work_links(material_row_id);
create index ix_work_links_work on public.estimate_work_links(work_row_id);
create index ix_price_results_revision on public.current_price_row_results(revision_id,estimate_row_id);
create index ix_gpr_months_plan on public.gpr_months(plan_id,month);
create index ix_gpr_assignments_plan_month on public.gpr_row_assignments(plan_id,month_id);
create index ix_gpr_assignments_row on public.gpr_row_assignments(estimate_row_id);
create index ix_supplier_items_catalog on public.supplier_items(project_id,catalog_item_id) where archived_at is null;
create index ix_supplier_prices_item_date on public.supplier_prices(supplier_item_id,effective_from desc);
create index ix_supply_docs_project_date on public.supply_documents(project_id,receipt_date desc);
create index ix_supply_lines_doc on public.supply_document_lines(document_id,sort_order);
create index ix_supply_lines_catalog on public.supply_document_lines(project_id,catalog_item_id);
create index ix_supply_alloc_white on public.supply_line_allocations(white_line_id);
create index ix_supply_alloc_green on public.supply_line_allocations(green_line_id);
create index ix_montage_spec_date on public.montage_events(specification_row_id,event_date);
create index ix_avr_docs_project_month on public.avr_documents(project_id,period_month);
create index ix_avr_rows_version on public.avr_rows(version_id);
create index ix_accounting_import_code on public.accounting_rows(import_id,material_code);
create index ix_s29_rows_doc on public.s29_rows(document_id);
create index ix_s29_carryover_project_item on public.s29_carryovers(project_id,catalog_item_id,origin_month);
create index ix_s29_settlement_carryover on public.s29_carryover_settlements(carryover_id);

do $$
declare t text;
begin
 foreach t in array array[
  'projects','catalog_items','specification_sections','specification_rows','specification_quantities',
  'estimates','estimate_sections','estimate_rows','estimate_row_costs','reconciliation_links',
  'reconciliation_journal','estimate_work_links','current_price_settings','current_price_row_overrides',
  'gpr_plans','gpr_months','gpr_floor_assignments','gpr_row_assignments','suppliers','supplier_items',
  'supply_documents','supply_document_lines','supply_line_allocations','montage_events','avr_documents',
  'accounting_code_links','s29_documents'
 ] loop
  execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function private.set_updated_at()',t,t);
 end loop;
end $$;

create or replace function private.is_project_member(p_project_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select p_project_id is not null and exists(
 select 1 from public.project_members pm
 where pm.project_id=p_project_id and pm.user_id=(select auth.uid())
); $$;

create or replace function private.can_edit_project(p_project_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select p_project_id is not null and exists(
 select 1 from public.project_members pm
 where pm.project_id=p_project_id and pm.user_id=(select auth.uid())
 and pm.access_role in('owner','editor')
); $$;

create or replace function private.is_project_owner(p_project_id uuid)
returns boolean language sql stable security definer set search_path=''
as $$ select p_project_id is not null and exists(
 select 1 from public.project_members pm
 where pm.project_id=p_project_id and pm.user_id=(select auth.uid())
 and pm.access_role='owner'
); $$;

create or replace function private.bootstrap_project_owner()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
 if new.created_by is not null then
  insert into public.project_members(project_id,user_id,access_role)
  values(new.id,new.created_by,'owner')
  on conflict(project_id,user_id) do nothing;
 end if;
 return new;
end;
$$;

create trigger trg_projects_bootstrap_owner
after insert on public.projects for each row execute function private.bootstrap_project_owner();

alter table public.projects enable row level security;
alter table public.project_members enable row level security;

create policy projects_select_member on public.projects for select to authenticated
 using((select private.is_project_member(id)));
create policy projects_insert_self on public.projects for insert to authenticated
 with check(created_by=(select auth.uid()));
create policy projects_update_owner on public.projects for update to authenticated
 using((select private.is_project_owner(id))) with check((select private.is_project_owner(id)));
create policy projects_delete_owner on public.projects for delete to authenticated
 using((select private.is_project_owner(id)));

create policy project_members_select_member on public.project_members for select to authenticated
 using((select private.is_project_member(project_id)));
create policy project_members_insert_owner on public.project_members for insert to authenticated
 with check((select private.is_project_owner(project_id)));
create policy project_members_update_owner on public.project_members for update to authenticated
 using((select private.is_project_owner(project_id))) with check((select private.is_project_owner(project_id)));
create policy project_members_delete_owner on public.project_members for delete to authenticated
 using((select private.is_project_owner(project_id)));

do $$
declare t text;
begin
 foreach t in array array[
  'project_files','project_file_links','imports','import_rows','audit_events',
  'catalog_items','specification_sections','specification_rows','specification_quantities',
  'estimates','estimate_sections','estimate_rows','estimate_row_costs','estimate_notes',
  'reconciliation_links','reconciliation_journal','estimate_work_links',
  'current_price_settings','current_price_row_overrides','current_price_revisions','current_price_row_results',
  'gpr_plans','gpr_plan_estimates','gpr_months','gpr_floor_assignments','gpr_row_assignments',
  'suppliers','supplier_items','supplier_prices','supply_documents','supply_document_lines','supply_line_allocations',
  'montage_events','avr_documents','avr_versions','avr_rows',
  'accounting_rows','accounting_code_links','accounting_period_sources',
  's29_documents','s29_rows','s29_allocations','s29_carryovers','s29_carryover_settlements'
 ] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('create policy %I_select on public.%I for select to authenticated using ((select private.is_project_member(project_id)))',t,t);
  execute format('create policy %I_insert on public.%I for insert to authenticated with check ((select private.can_edit_project(project_id)))',t,t);
  execute format('create policy %I_update on public.%I for update to authenticated using ((select private.can_edit_project(project_id))) with check ((select private.can_edit_project(project_id)))',t,t);
  execute format('create policy %I_delete on public.%I for delete to authenticated using ((select private.can_edit_project(project_id)))',t,t);
 end loop;
end $$;

drop policy if exists audit_events_update on public.audit_events;
drop policy if exists audit_events_delete on public.audit_events;

grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant select on public.v_s29_carryover_balances to authenticated;
grant usage,select on all sequences in schema public to authenticated;

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant usage on schema private to authenticated;
grant execute on function private.is_project_member(uuid) to authenticated;
grant execute on function private.can_edit_project(uuid) to authenticated;
grant execute on function private.is_project_owner(uuid) to authenticated;
grant execute on function private.try_uuid(text) to authenticated;
revoke execute on function private.bootstrap_project_owner() from public,anon,authenticated;
